// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymeoglaoccsstbwbqicq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltZW9nbGFvY2Nzc3Rid2JxaWNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MjgxNDQsImV4cCI6MjA2MjAwNDE0NH0.08zMmn-gLm4-2_7odg5-gC25sSmyrP8iZKZu6qBqLAo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create client with better error handling for offline scenarios
const supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: false, // Disable auto refresh to prevent background errors
    persistSession: true,
    detectSessionInUrl: false
  },
  global: {
    fetch: (url, options = {}) => {
      return fetch(url, options).catch((error) => {
        // Silently handle network errors to prevent console spam
        if (error.name === 'TypeError' && error.message.includes('Failed to fetch')) {
          return Promise.reject(error);
        }
        throw error;
      });
    }
  }
});

export const supabase = supabaseClient;